server:
  port: 8081
  #  tomcat:
  #    uri-encoding: utf-8
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

spring:
  mvc:
    servlet:
      load-on-startup: 10
    log-request-details: true

  profiles:
    active: dev
    group:
      "dev": rocketmq, redis, mongodb, im

logging:
  level:
    web: info