rocketmq:
  name-server: localhost:9876
  im-message-topic: im-message-topic
  user-message-topic: user-message-topic
  group-message-topic: group-message-topic
  consumer:
    user-message-group: user-message-consumer-group
    group-message-group: group-message-consumer-group
    im-message-group: im-message-consumer-group
#  producer:
#    group: im-message-producer-group
#    send-message-timeout: 3000
#    retry-times-when-send-failed: 3
#    max-message-size: 3

