spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/im_practice?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    druid:
      db-type: mysql
    type: com.alibaba.druid.pool.DruidDataSource

