spring:
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      timeout: 10s
      client-type: lettuce
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0